PART_ID: ''
N_TRIALS_TRAIN: 40
N_TRAILS_EXP: 100
REACTION_KEYS: ['left', 'right']
RESULTS: [["PART_ID", "EXPERIMENT", "ACC", "RT", "TRIAL_TYPE", "REACTION"]]
STIM_TIME: 2
STOP_TIME: 1
LIM_MAX: 1.5
LIM_MIN: 0.5
